// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogsForAllGuilds = `-- name: CountAuditLogsForAllGuilds :many
SELECT guild_id, COUNT(*) AS count
FROM audit_logs
GROUP BY guild_id
`

type CountAuditLogsForAllGuildsRow struct {
	GuildID string `json:"guild_id"`
	Count   int64  `json:"count"`
}

func (q *Queries) CountAuditLogsForAllGuilds(ctx context.Context) ([]CountAuditLogsForAllGuildsRow, error) {
	rows, err := q.db.Query(ctx, countAuditLogsForAllGuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAuditLogsForAllGuildsRow
	for rows.Next() {
		var i CountAuditLogsForAllGuildsRow
		if err := rows.Scan(&i.GuildID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditLogsForGuild = `-- name: CountAuditLogsForGuild :one
SELECT COUNT(*) FROM audit_logs WHERE guild_id = $1
`

func (q *Queries) CountAuditLogsForGuild(ctx context.Context, guildID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsForGuild, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (guild_id, action, actor_id, actor_name, target_id, target_name, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, guild_id, action, actor_id, target_id, metadata, created_at, actor_name, target_name
`

type CreateAuditLogParams struct {
	GuildID    string      `json:"guild_id"`
	Action     string      `json:"action"`
	ActorID    string      `json:"actor_id"`
	ActorName  string      `json:"actor_name"`
	TargetID   pgtype.Text `json:"target_id"`
	TargetName string      `json:"target_name"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.GuildID,
		arg.Action,
		arg.ActorID,
		arg.ActorName,
		arg.TargetID,
		arg.TargetName,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Action,
		&i.ActorID,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
		&i.ActorName,
		&i.TargetName,
	)
	return i, err
}

const deleteAuditLogsBefore = `-- name: DeleteAuditLogsBefore :exec
DELETE FROM audit_logs WHERE created_at < $1
`

func (q *Queries) DeleteAuditLogsBefore(ctx context.Context, cutoff pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteAuditLogsBefore, cutoff)
	return err
}

const deleteMessageLogsBefore = `-- name: DeleteMessageLogsBefore :exec
DELETE FROM audit_logs WHERE action LIKE 'MESSAGE_%' AND created_at < $1
`

// Retention prune for message-content logs only (MESSAGE_CREATE etc.); leaves
// moderation audit entries untouched.
func (q *Queries) DeleteMessageLogsBefore(ctx context.Context, cutoff pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteMessageLogsBefore, cutoff)
	return err
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, guild_id, action, actor_id, target_id, metadata, created_at, actor_name, target_name FROM audit_logs
WHERE guild_id = $1 AND actor_id = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListAuditLogsByActorParams struct {
	GuildID    string `json:"guild_id"`
	ActorID    string `json:"actor_id"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByActor,
		arg.GuildID,
		arg.ActorID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Action,
			&i.ActorID,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorName,
			&i.TargetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsForGuild = `-- name: ListAuditLogsForGuild :many
SELECT id, guild_id, action, actor_id, target_id, metadata, created_at, actor_name, target_name FROM audit_logs
WHERE guild_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAuditLogsForGuildParams struct {
	GuildID    string `json:"guild_id"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) ListAuditLogsForGuild(ctx context.Context, arg ListAuditLogsForGuildParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForGuild, arg.GuildID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Action,
			&i.ActorID,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorName,
			&i.TargetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
