// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogsForGuild = `-- name: CountAuditLogsForGuild :one
SELECT COUNT(*) FROM audit_logs WHERE guild_id = $1
`

func (q *Queries) CountAuditLogsForGuild(ctx context.Context, guildID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsForGuild, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (guild_id, action, actor_id, target_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, guild_id, action, actor_id, target_id, metadata, created_at
`

type CreateAuditLogParams struct {
	GuildID  string      `json:"guild_id"`
	Action   string      `json:"action"`
	ActorID  string      `json:"actor_id"`
	TargetID pgtype.Text `json:"target_id"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.GuildID,
		arg.Action,
		arg.ActorID,
		arg.TargetID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Action,
		&i.ActorID,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuditLogsBefore = `-- name: DeleteAuditLogsBefore :exec
DELETE FROM audit_logs WHERE created_at < $1
`

func (q *Queries) DeleteAuditLogsBefore(ctx context.Context, cutoff pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteAuditLogsBefore, cutoff)
	return err
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, guild_id, action, actor_id, target_id, metadata, created_at FROM audit_logs
WHERE guild_id = $1 AND actor_id = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListAuditLogsByActorParams struct {
	GuildID    string `json:"guild_id"`
	ActorID    string `json:"actor_id"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByActor,
		arg.GuildID,
		arg.ActorID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Action,
			&i.ActorID,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsForGuild = `-- name: ListAuditLogsForGuild :many
SELECT id, guild_id, action, actor_id, target_id, metadata, created_at FROM audit_logs
WHERE guild_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAuditLogsForGuildParams struct {
	GuildID    string `json:"guild_id"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) ListAuditLogsForGuild(ctx context.Context, arg ListAuditLogsForGuildParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForGuild, arg.GuildID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Action,
			&i.ActorID,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
