// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: birthdays.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBirthday = `-- name: DeleteBirthday :exec
DELETE FROM birthdays WHERE guild_id = $1 AND user_id = $2
`

type DeleteBirthdayParams struct {
	GuildID string `json:"guild_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) DeleteBirthday(ctx context.Context, arg DeleteBirthdayParams) error {
	_, err := q.db.Exec(ctx, deleteBirthday, arg.GuildID, arg.UserID)
	return err
}

const getBirthday = `-- name: GetBirthday :one
SELECT id, guild_id, user_id, birthday, created_at, updated_at FROM birthdays WHERE guild_id = $1 AND user_id = $2
`

type GetBirthdayParams struct {
	GuildID string `json:"guild_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) GetBirthday(ctx context.Context, arg GetBirthdayParams) (Birthday, error) {
	row := q.db.QueryRow(ctx, getBirthday, arg.GuildID, arg.UserID)
	var i Birthday
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.UserID,
		&i.Birthday,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBirthdaysByGuild = `-- name: ListBirthdaysByGuild :many
SELECT id, guild_id, user_id, birthday, created_at, updated_at FROM birthdays
WHERE guild_id = $1
ORDER BY birthday ASC
`

func (q *Queries) ListBirthdaysByGuild(ctx context.Context, guildID string) ([]Birthday, error) {
	rows, err := q.db.Query(ctx, listBirthdaysByGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Birthday
	for rows.Next() {
		var i Birthday
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.UserID,
			&i.Birthday,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBirthdaysTodayByGuild = `-- name: ListBirthdaysTodayByGuild :many
SELECT id, guild_id, user_id, birthday, created_at, updated_at FROM birthdays
WHERE guild_id = $1
  AND EXTRACT(MONTH FROM birthday) = $2::int
  AND EXTRACT(DAY FROM birthday) = $3::int
`

type ListBirthdaysTodayByGuildParams struct {
	GuildID string `json:"guild_id"`
	Month   int32  `json:"month"`
	Day     int32  `json:"day"`
}

func (q *Queries) ListBirthdaysTodayByGuild(ctx context.Context, arg ListBirthdaysTodayByGuildParams) ([]Birthday, error) {
	rows, err := q.db.Query(ctx, listBirthdaysTodayByGuild, arg.GuildID, arg.Month, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Birthday
	for rows.Next() {
		var i Birthday
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.UserID,
			&i.Birthday,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBirthday = `-- name: UpsertBirthday :one
INSERT INTO birthdays (guild_id, user_id, birthday)
VALUES ($1, $2, $3)
ON CONFLICT (guild_id, user_id) DO UPDATE
SET birthday = EXCLUDED.birthday,
    updated_at = NOW()
RETURNING id, guild_id, user_id, birthday, created_at, updated_at
`

type UpsertBirthdayParams struct {
	GuildID  string      `json:"guild_id"`
	UserID   string      `json:"user_id"`
	Birthday pgtype.Date `json:"birthday"`
}

func (q *Queries) UpsertBirthday(ctx context.Context, arg UpsertBirthdayParams) (Birthday, error) {
	row := q.db.QueryRow(ctx, upsertBirthday, arg.GuildID, arg.UserID, arg.Birthday)
	var i Birthday
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.UserID,
		&i.Birthday,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
