// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleted_messages.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDeletedMessagesForAllGuilds = `-- name: CountDeletedMessagesForAllGuilds :many
SELECT guild_id, COUNT(*) AS count
FROM deleted_messages
GROUP BY guild_id
`

type CountDeletedMessagesForAllGuildsRow struct {
	GuildID string `json:"guild_id"`
	Count   int64  `json:"count"`
}

func (q *Queries) CountDeletedMessagesForAllGuilds(ctx context.Context) ([]CountDeletedMessagesForAllGuildsRow, error) {
	rows, err := q.db.Query(ctx, countDeletedMessagesForAllGuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDeletedMessagesForAllGuildsRow
	for rows.Next() {
		var i CountDeletedMessagesForAllGuildsRow
		if err := rows.Scan(&i.GuildID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDeletedMessagesForGuild = `-- name: CountDeletedMessagesForGuild :one
SELECT COUNT(*) FROM deleted_messages
WHERE guild_id = $1
`

func (q *Queries) CountDeletedMessagesForGuild(ctx context.Context, guildID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDeletedMessagesForGuild, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeletedMessagesBefore = `-- name: DeleteDeletedMessagesBefore :exec
DELETE FROM deleted_messages WHERE created_at < $1
`

func (q *Queries) DeleteDeletedMessagesBefore(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteDeletedMessagesBefore, createdAt)
	return err
}

const insertDeletedMessage = `-- name: InsertDeletedMessage :one
INSERT INTO deleted_messages (guild_id, channel_id, message_id, author_id, author_name, content, attachments, deleted_by, deleted_by_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, guild_id, channel_id, message_id, author_id, author_name, content, attachments, deleted_by, deleted_by_name, created_at
`

type InsertDeletedMessageParams struct {
	GuildID       string `json:"guild_id"`
	ChannelID     string `json:"channel_id"`
	MessageID     string `json:"message_id"`
	AuthorID      string `json:"author_id"`
	AuthorName    string `json:"author_name"`
	Content       string `json:"content"`
	Attachments   []byte `json:"attachments"`
	DeletedBy     string `json:"deleted_by"`
	DeletedByName string `json:"deleted_by_name"`
}

func (q *Queries) InsertDeletedMessage(ctx context.Context, arg InsertDeletedMessageParams) (DeletedMessage, error) {
	row := q.db.QueryRow(ctx, insertDeletedMessage,
		arg.GuildID,
		arg.ChannelID,
		arg.MessageID,
		arg.AuthorID,
		arg.AuthorName,
		arg.Content,
		arg.Attachments,
		arg.DeletedBy,
		arg.DeletedByName,
	)
	var i DeletedMessage
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.AuthorID,
		&i.AuthorName,
		&i.Content,
		&i.Attachments,
		&i.DeletedBy,
		&i.DeletedByName,
		&i.CreatedAt,
	)
	return i, err
}

const listDeletedMessagesForChannel = `-- name: ListDeletedMessagesForChannel :many
SELECT id, guild_id, channel_id, message_id, author_id, author_name, content, attachments, deleted_by, deleted_by_name, created_at FROM deleted_messages
WHERE guild_id = $1 AND channel_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListDeletedMessagesForChannelParams struct {
	GuildID   string `json:"guild_id"`
	ChannelID string `json:"channel_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListDeletedMessagesForChannel(ctx context.Context, arg ListDeletedMessagesForChannelParams) ([]DeletedMessage, error) {
	rows, err := q.db.Query(ctx, listDeletedMessagesForChannel,
		arg.GuildID,
		arg.ChannelID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeletedMessage
	for rows.Next() {
		var i DeletedMessage
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Content,
			&i.Attachments,
			&i.DeletedBy,
			&i.DeletedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedMessagesForGuild = `-- name: ListDeletedMessagesForGuild :many
SELECT id, guild_id, channel_id, message_id, author_id, author_name, content, attachments, deleted_by, deleted_by_name, created_at FROM deleted_messages
WHERE guild_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDeletedMessagesForGuildParams struct {
	GuildID string `json:"guild_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListDeletedMessagesForGuild(ctx context.Context, arg ListDeletedMessagesForGuildParams) ([]DeletedMessage, error) {
	rows, err := q.db.Query(ctx, listDeletedMessagesForGuild, arg.GuildID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeletedMessage
	for rows.Next() {
		var i DeletedMessage
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Content,
			&i.Attachments,
			&i.DeletedBy,
			&i.DeletedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
