// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diary_entries.sql

package postgres

import (
	"context"
)

const createDiaryEntry = `-- name: CreateDiaryEntry :one
INSERT INTO diary_entries (user_id, content)
VALUES ($1, $2)
RETURNING id, user_id, content, created_at
`

type CreateDiaryEntryParams struct {
	UserID  string `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateDiaryEntry(ctx context.Context, arg CreateDiaryEntryParams) (DiaryEntry, error) {
	row := q.db.QueryRow(ctx, createDiaryEntry, arg.UserID, arg.Content)
	var i DiaryEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDiaryEntry = `-- name: DeleteDiaryEntry :exec
DELETE FROM diary_entries WHERE id = $1 AND user_id = $2
`

type DeleteDiaryEntryParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDiaryEntry(ctx context.Context, arg DeleteDiaryEntryParams) error {
	_, err := q.db.Exec(ctx, deleteDiaryEntry, arg.ID, arg.UserID)
	return err
}

const getDiaryEntry = `-- name: GetDiaryEntry :one
SELECT id, user_id, content, created_at FROM diary_entries WHERE id = $1 AND user_id = $2
`

type GetDiaryEntryParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetDiaryEntry(ctx context.Context, arg GetDiaryEntryParams) (DiaryEntry, error) {
	row := q.db.QueryRow(ctx, getDiaryEntry, arg.ID, arg.UserID)
	var i DiaryEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listDiaryEntriesByUser = `-- name: ListDiaryEntriesByUser :many
SELECT id, user_id, content, created_at FROM diary_entries
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDiaryEntriesByUser(ctx context.Context, userID string) ([]DiaryEntry, error) {
	rows, err := q.db.Query(ctx, listDiaryEntriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiaryEntry
	for rows.Next() {
		var i DiaryEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
