// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guilds.sql

package postgres

import (
	"context"
)

const createGuild = `-- name: CreateGuild :one
INSERT INTO guilds (id, name, premium_tier)
VALUES ($1, $2, $3)
RETURNING id, name, created_at, premium_tier
`

type CreateGuildParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	PremiumTier int32  `json:"premium_tier"`
}

func (q *Queries) CreateGuild(ctx context.Context, arg CreateGuildParams) (Guild, error) {
	row := q.db.QueryRow(ctx, createGuild, arg.ID, arg.Name, arg.PremiumTier)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.PremiumTier,
	)
	return i, err
}

const deleteGuild = `-- name: DeleteGuild :exec
DELETE FROM guilds WHERE id = $1
`

func (q *Queries) DeleteGuild(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGuild, id)
	return err
}

const getGuild = `-- name: GetGuild :one
SELECT id, name, created_at, premium_tier FROM guilds WHERE id = $1
`

func (q *Queries) GetGuild(ctx context.Context, id string) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuild, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.PremiumTier,
	)
	return i, err
}

const listGuilds = `-- name: ListGuilds :many
SELECT id, name, created_at, premium_tier FROM guilds ORDER BY created_at DESC
`

func (q *Queries) ListGuilds(ctx context.Context) ([]Guild, error) {
	rows, err := q.db.Query(ctx, listGuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guild
	for rows.Next() {
		var i Guild
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.PremiumTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuild = `-- name: UpdateGuild :one
UPDATE guilds
SET name = $1,
    premium_tier = $2
WHERE id = $3
RETURNING id, name, created_at, premium_tier
`

type UpdateGuildParams struct {
	Name        string `json:"name"`
	PremiumTier int32  `json:"premium_tier"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateGuild(ctx context.Context, arg UpdateGuildParams) (Guild, error) {
	row := q.db.QueryRow(ctx, updateGuild, arg.Name, arg.PremiumTier, arg.ID)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.PremiumTier,
	)
	return i, err
}
