// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guild_birthday_settings.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGuildBirthdaySettings = `-- name: GetGuildBirthdaySettings :one
SELECT guild_id, channel_id, role_id, updated_at FROM guild_birthday_settings WHERE guild_id = $1
`

func (q *Queries) GetGuildBirthdaySettings(ctx context.Context, guildID string) (GuildBirthdaySetting, error) {
	row := q.db.QueryRow(ctx, getGuildBirthdaySettings, guildID)
	var i GuildBirthdaySetting
	err := row.Scan(
		&i.GuildID,
		&i.ChannelID,
		&i.RoleID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGuildBirthdayChannel = `-- name: UpsertGuildBirthdayChannel :one
INSERT INTO guild_birthday_settings (guild_id, channel_id)
VALUES ($1, $2)
ON CONFLICT (guild_id) DO UPDATE
SET channel_id = EXCLUDED.channel_id,
    updated_at = NOW()
RETURNING guild_id, channel_id, role_id, updated_at
`

type UpsertGuildBirthdayChannelParams struct {
	GuildID   string      `json:"guild_id"`
	ChannelID pgtype.Text `json:"channel_id"`
}

func (q *Queries) UpsertGuildBirthdayChannel(ctx context.Context, arg UpsertGuildBirthdayChannelParams) (GuildBirthdaySetting, error) {
	row := q.db.QueryRow(ctx, upsertGuildBirthdayChannel, arg.GuildID, arg.ChannelID)
	var i GuildBirthdaySetting
	err := row.Scan(
		&i.GuildID,
		&i.ChannelID,
		&i.RoleID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGuildBirthdayRole = `-- name: UpsertGuildBirthdayRole :one
INSERT INTO guild_birthday_settings (guild_id, role_id)
VALUES ($1, $2)
ON CONFLICT (guild_id) DO UPDATE
SET role_id = EXCLUDED.role_id,
    updated_at = NOW()
RETURNING guild_id, channel_id, role_id, updated_at
`

type UpsertGuildBirthdayRoleParams struct {
	GuildID string      `json:"guild_id"`
	RoleID  pgtype.Text `json:"role_id"`
}

func (q *Queries) UpsertGuildBirthdayRole(ctx context.Context, arg UpsertGuildBirthdayRoleParams) (GuildBirthdaySetting, error) {
	row := q.db.QueryRow(ctx, upsertGuildBirthdayRole, arg.GuildID, arg.RoleID)
	var i GuildBirthdaySetting
	err := row.Scan(
		&i.GuildID,
		&i.ChannelID,
		&i.RoleID,
		&i.UpdatedAt,
	)
	return i, err
}
