// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guild_settings.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGuildSettings = `-- name: DeleteGuildSettings :exec
DELETE FROM guild_settings WHERE guild_id = $1
`

func (q *Queries) DeleteGuildSettings(ctx context.Context, guildID string) error {
	_, err := q.db.Exec(ctx, deleteGuildSettings, guildID)
	return err
}

const getGuildSettings = `-- name: GetGuildSettings :one
SELECT guild_id, prefix, language, auto_moderation_enabled, logging_channel_id, updated_at, message_logging_enabled FROM guild_settings WHERE guild_id = $1
`

func (q *Queries) GetGuildSettings(ctx context.Context, guildID string) (GuildSetting, error) {
	row := q.db.QueryRow(ctx, getGuildSettings, guildID)
	var i GuildSetting
	err := row.Scan(
		&i.GuildID,
		&i.Prefix,
		&i.Language,
		&i.AutoModerationEnabled,
		&i.LoggingChannelID,
		&i.UpdatedAt,
		&i.MessageLoggingEnabled,
	)
	return i, err
}

const updateGuildSettings = `-- name: UpdateGuildSettings :one
UPDATE guild_settings
SET prefix = $1,
    language = $2,
    auto_moderation_enabled = $3,
    logging_channel_id = $4,
    message_logging_enabled = $5,
    updated_at = NOW()
WHERE guild_id = $6
RETURNING guild_id, prefix, language, auto_moderation_enabled, logging_channel_id, updated_at, message_logging_enabled
`

type UpdateGuildSettingsParams struct {
	Prefix                string      `json:"prefix"`
	Language              string      `json:"language"`
	AutoModerationEnabled bool        `json:"auto_moderation_enabled"`
	LoggingChannelID      pgtype.Text `json:"logging_channel_id"`
	MessageLoggingEnabled bool        `json:"message_logging_enabled"`
	GuildID               string      `json:"guild_id"`
}

func (q *Queries) UpdateGuildSettings(ctx context.Context, arg UpdateGuildSettingsParams) (GuildSetting, error) {
	row := q.db.QueryRow(ctx, updateGuildSettings,
		arg.Prefix,
		arg.Language,
		arg.AutoModerationEnabled,
		arg.LoggingChannelID,
		arg.MessageLoggingEnabled,
		arg.GuildID,
	)
	var i GuildSetting
	err := row.Scan(
		&i.GuildID,
		&i.Prefix,
		&i.Language,
		&i.AutoModerationEnabled,
		&i.LoggingChannelID,
		&i.UpdatedAt,
		&i.MessageLoggingEnabled,
	)
	return i, err
}

const upsertGuildSettings = `-- name: UpsertGuildSettings :one
INSERT INTO guild_settings (guild_id, prefix, language, auto_moderation_enabled, logging_channel_id, message_logging_enabled)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (guild_id) DO UPDATE
SET prefix = EXCLUDED.prefix,
    language = EXCLUDED.language,
    auto_moderation_enabled = EXCLUDED.auto_moderation_enabled,
    logging_channel_id = EXCLUDED.logging_channel_id,
    message_logging_enabled = EXCLUDED.message_logging_enabled,
    updated_at = NOW()
RETURNING guild_id, prefix, language, auto_moderation_enabled, logging_channel_id, updated_at, message_logging_enabled
`

type UpsertGuildSettingsParams struct {
	GuildID               string      `json:"guild_id"`
	Prefix                string      `json:"prefix"`
	Language              string      `json:"language"`
	AutoModerationEnabled bool        `json:"auto_moderation_enabled"`
	LoggingChannelID      pgtype.Text `json:"logging_channel_id"`
	MessageLoggingEnabled bool        `json:"message_logging_enabled"`
}

func (q *Queries) UpsertGuildSettings(ctx context.Context, arg UpsertGuildSettingsParams) (GuildSetting, error) {
	row := q.db.QueryRow(ctx, upsertGuildSettings,
		arg.GuildID,
		arg.Prefix,
		arg.Language,
		arg.AutoModerationEnabled,
		arg.LoggingChannelID,
		arg.MessageLoggingEnabled,
	)
	var i GuildSetting
	err := row.Scan(
		&i.GuildID,
		&i.Prefix,
		&i.Language,
		&i.AutoModerationEnabled,
		&i.LoggingChannelID,
		&i.UpdatedAt,
		&i.MessageLoggingEnabled,
	)
	return i, err
}
