// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int64              `json:"id"`
	GuildID   string             `json:"guild_id"`
	Action    string             `json:"action"`
	ActorID   string             `json:"actor_id"`
	TargetID  pgtype.Text        `json:"target_id"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Guild struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PremiumTier int32              `json:"premium_tier"`
}

type GuildSetting struct {
	GuildID               string             `json:"guild_id"`
	Prefix                string             `json:"prefix"`
	Language              string             `json:"language"`
	AutoModerationEnabled bool               `json:"auto_moderation_enabled"`
	LoggingChannelID      pgtype.Text        `json:"logging_channel_id"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type UserPermission struct {
	ID              int64              `json:"id"`
	UserID          string             `json:"user_id"`
	GuildID         string             `json:"guild_id"`
	Role            string             `json:"role"`
	PermissionsJson []byte             `json:"permissions_json"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
