// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         int64              `json:"id"`
	GuildID    string             `json:"guild_id"`
	Action     string             `json:"action"`
	ActorID    string             `json:"actor_id"`
	TargetID   pgtype.Text        `json:"target_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ActorName  string             `json:"actor_name"`
	TargetName string             `json:"target_name"`
}

type Birthday struct {
	ID        int64              `json:"id"`
	GuildID   string             `json:"guild_id"`
	UserID    string             `json:"user_id"`
	Birthday  pgtype.Date        `json:"birthday"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DeletedMessage struct {
	ID            int64              `json:"id"`
	GuildID       string             `json:"guild_id"`
	ChannelID     string             `json:"channel_id"`
	MessageID     string             `json:"message_id"`
	AuthorID      string             `json:"author_id"`
	AuthorName    string             `json:"author_name"`
	Content       string             `json:"content"`
	Attachments   []byte             `json:"attachments"`
	DeletedBy     string             `json:"deleted_by"`
	DeletedByName string             `json:"deleted_by_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type DiaryEntry struct {
	ID        int64              `json:"id"`
	UserID    string             `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Guild struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PremiumTier int32              `json:"premium_tier"`
}

type GuildBirthdaySetting struct {
	GuildID   string             `json:"guild_id"`
	ChannelID pgtype.Text        `json:"channel_id"`
	RoleID    pgtype.Text        `json:"role_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type GuildSetting struct {
	GuildID               string             `json:"guild_id"`
	Prefix                string             `json:"prefix"`
	Language              string             `json:"language"`
	AutoModerationEnabled bool               `json:"auto_moderation_enabled"`
	LoggingChannelID      pgtype.Text        `json:"logging_channel_id"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	UserID       string             `json:"user_id"`
	Email        pgtype.Text        `json:"email"`
	Passwordhash pgtype.Text        `json:"passwordhash"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserPermission struct {
	ID              int64              `json:"id"`
	UserID          string             `json:"user_id"`
	GuildID         string             `json:"guild_id"`
	Role            string             `json:"role"`
	PermissionsJson []byte             `json:"permissions_json"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
