// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_permissions.sql

package postgres

import (
	"context"
)

const deleteUserPermission = `-- name: DeleteUserPermission :exec
DELETE FROM user_permissions
WHERE user_id = $1 AND guild_id = $2 AND role = $3
`

type DeleteUserPermissionParams struct {
	UserID  string `json:"user_id"`
	GuildID string `json:"guild_id"`
	Role    string `json:"role"`
}

func (q *Queries) DeleteUserPermission(ctx context.Context, arg DeleteUserPermissionParams) error {
	_, err := q.db.Exec(ctx, deleteUserPermission, arg.UserID, arg.GuildID, arg.Role)
	return err
}

const getUserPermission = `-- name: GetUserPermission :one
SELECT id, user_id, guild_id, role, permissions_json, created_at FROM user_permissions
WHERE user_id = $1 AND guild_id = $2 AND role = $3
`

type GetUserPermissionParams struct {
	UserID  string `json:"user_id"`
	GuildID string `json:"guild_id"`
	Role    string `json:"role"`
}

func (q *Queries) GetUserPermission(ctx context.Context, arg GetUserPermissionParams) (UserPermission, error) {
	row := q.db.QueryRow(ctx, getUserPermission, arg.UserID, arg.GuildID, arg.Role)
	var i UserPermission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuildID,
		&i.Role,
		&i.PermissionsJson,
		&i.CreatedAt,
	)
	return i, err
}

const listUserPermissionsForGuild = `-- name: ListUserPermissionsForGuild :many
SELECT id, user_id, guild_id, role, permissions_json, created_at FROM user_permissions
WHERE guild_id = $1
ORDER BY user_id, role
`

func (q *Queries) ListUserPermissionsForGuild(ctx context.Context, guildID string) ([]UserPermission, error) {
	rows, err := q.db.Query(ctx, listUserPermissionsForGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPermission
	for rows.Next() {
		var i UserPermission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuildID,
			&i.Role,
			&i.PermissionsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionsForUser = `-- name: ListUserPermissionsForUser :many
SELECT id, user_id, guild_id, role, permissions_json, created_at FROM user_permissions
WHERE user_id = $1 AND guild_id = $2
ORDER BY role
`

type ListUserPermissionsForUserParams struct {
	UserID  string `json:"user_id"`
	GuildID string `json:"guild_id"`
}

func (q *Queries) ListUserPermissionsForUser(ctx context.Context, arg ListUserPermissionsForUserParams) ([]UserPermission, error) {
	rows, err := q.db.Query(ctx, listUserPermissionsForUser, arg.UserID, arg.GuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPermission
	for rows.Next() {
		var i UserPermission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuildID,
			&i.Role,
			&i.PermissionsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserPermission = `-- name: UpsertUserPermission :one
INSERT INTO user_permissions (user_id, guild_id, role, permissions_json)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, guild_id, role) DO UPDATE
SET permissions_json = EXCLUDED.permissions_json
RETURNING id, user_id, guild_id, role, permissions_json, created_at
`

type UpsertUserPermissionParams struct {
	UserID          string `json:"user_id"`
	GuildID         string `json:"guild_id"`
	Role            string `json:"role"`
	PermissionsJson []byte `json:"permissions_json"`
}

func (q *Queries) UpsertUserPermission(ctx context.Context, arg UpsertUserPermissionParams) (UserPermission, error) {
	row := q.db.QueryRow(ctx, upsertUserPermission,
		arg.UserID,
		arg.GuildID,
		arg.Role,
		arg.PermissionsJson,
	)
	var i UserPermission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuildID,
		&i.Role,
		&i.PermissionsJson,
		&i.CreatedAt,
	)
	return i, err
}
